// FACILITIES
export const FETCH_FACILITIES = 'facilities/FETCH_FACILITIES';
export const RECEIVE_FACILITIES = 'facilities/RECEIVE_FACILITIES';
export const RECEIVE_FACILITIES_FAILED = 'facilities/RECEIVE_FACILITIES_FAILED';
