// FACILITIES
export const FETCH_FACILITIES = 'FETCH_FACILITIES';
export const RECEIVE_FACILITIES = 'RECEIVE_FACILITIES';
export const RECEIVE_FACILITIES_FAILED = 'RECEIVE_FACILITIES_FAILED';

// UNITS (FACILITY)
export const FETCH_UNITS = 'FETCH_UNITS';
export const RECEIVE_UNITS = 'RECEIVE_UNITS';
export const RECEIVE_UNITS_FAILED = 'RECEIVE_UNITS_FAILED';

// ALARMS (UNIT)
export const FETCH_ALARMS = 'FETCH_ALARMS';
export const RECEIVE_ALARMS = 'RECEIVE_ALARMS';
export const RECEIVE_ALARMS_FAILED = 'RECEIVE_ALARMS_FAILED';