// FACILITIES
export const FETCH_FACILITIES = 'FETCH_FACILITIES';
export const RECEIVE_FACILITIES = 'RECEIVE_FACILITIES';
export const RECEIVE_FACILITIES_FAILED = 'RECEIVE_FACILITIES_FAILED';

// UNITS
export const FETCH_UNITS = 'FETCH_UNITS';
export const RECEIVE_UNITS = 'RECEIVE_UNITS';
export const RECEIVE_UNITS_FAILED = 'RECEIVE_UNITS_FAILED';
